## 🎯 Exercícios 🎯 <a class="anchor" id="cinco"></a>
1) Transforme as duas listas em duas arrays diferentes arr1 e arr2.
2) Verifique o dtype dos array
3) Transforme os dois array em float
4) Compare as duas arrays e mostre os indices dos elementos que são iguais(dica = .where)
5) Retorne os numeros do array que são iguais usando o output do passo 4

In [2]:
import numpy as np

list_1 = [1,2,3,4,5]
list_2 = [1,3,2.2,4,5]

arr1 = np.array(list_1)
arr2 = np.array(list_2)

print(arr1.dtype)
print(arr2.dtype)

print(arr1.astype(float))
print(arr2.astype(float))

print(np.where(arr1 == arr2))

print(arr1[[0,3,4]])

int32
float64
[1. 2. 3. 4. 5.]
[1.  3.  2.2 4.  5. ]
(array([0, 3, 4], dtype=int64),)
[1 4 5]



1) Gere uma array com 3 dimensões com shape. (2,2,2)
2) Printe o ndim da array e o shape
3) Retire um elemento especifico [bloco][linha][coluna]



In [15]:
np.random.seed(1)
arr = np.floor(10*np.random.random_sample((2,2,2)))

print(arr)

print(arr.ndim)
print(arr.shape)

arr[1][1][0]


[[[4. 7.]
  [0. 3.]]

 [[1. 0.]
  [1. 3.]]]
3
(2, 2, 2)


1.0

#### DIY - Grupos

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

In [28]:
import pandas as pd

pd.read_csv(url,delimiter = ";")

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

DICA = Procure por nan e substitua por 0 (dica: is_nan e nan_to_num)

https://numpy.org/devdocs/user/basics.io.genfromtxt.html
1) Verifique a url e veja quais são as colunas do arquivo
2) Veja qual é o delimiter do arquivo ',' , ':', ';'
3) Selecione as colunas (param usecols) Citric Acid, PH e  Alcohol
4) Mostre o array e as caracteristicas dele ndim, shape, dtype
5) Procure o maximo e minimo da coluna PH 
6) Obtenha a media da coluna Alcohol

In [60]:
#Import data
wine_arr = np.genfromtxt(url, delimiter=";",usecols = (2,8,10),skip_header = 1)

# indexes = np.isnan(wine_arr)
# wine_arr[(indexes)] = 0

print(wine_arr)

[[ 0.    3.51  9.4 ]
 [ 0.    3.2   9.8 ]
 [ 0.04  3.26  9.8 ]
 ...
 [ 0.13  3.42 11.  ]
 [ 0.12  3.57 10.2 ]
 [ 0.47  3.39 11.  ]]


In [33]:
#Show array

print(wine_arr.ndim)

print(wine_arr.shape)

print(wine_arr.dtype)


2
(1599, 3)
float64


In [62]:
#Max e Min

maximo = wine_arr.max(axis = 0)[1]

minimo = wine_arr.min(axis = 0)[1]

print(f"Mínimo: {minimo} | Máximo: {maximo}")


Mínimo: 2.74 | Máximo: 4.01


In [64]:
#Media coluna Alcohol

media = wine_arr.mean(axis = 0)[2]
print(f"Média Alcohol: {media:.2f}%")

Média Alcohol: 10.42%


#### Extra

1) Faça um for loop que itere por todos os elementos de uma array de 3 dimensões

In [77]:
np.random.seed(1)
arr = np.random.randint(0,100,(3,2,2))

print(arr)

for index_i,i in enumerate(arr):
    for index_j,j in enumerate(i):
        for index_k,k in enumerate(j):
            print(f"[{index_i}, {index_j}, {index_k}] -> {k}")


[[[37 12]
  [72  9]]

 [[75  5]
  [79 64]]

 [[16  1]
  [76 71]]]
[0, 0, 0] -> 37
[0, 0, 1] -> 12
[0, 1, 0] -> 72
[0, 1, 1] -> 9
[1, 0, 0] -> 75
[1, 0, 1] -> 5
[1, 1, 0] -> 79
[1, 1, 1] -> 64
[2, 0, 0] -> 16
[2, 0, 1] -> 1
[2, 1, 0] -> 76
[2, 1, 1] -> 71
